# Generated by Django 2.2.2 on 2019-06-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipousuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipousuario', models.CharField(choices=[('D', 'Designer'), ('R', 'Revizador'), ('A', 'Administrador')], max_length=1)),
            ],
        ),
    ]
