# Generated by Django 2.2.2 on 2019-07-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdesigner', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LLN', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('BG', 'BeyondGroup'), ('AMEX', 'AmericanExpress'), ('NS', 'NacioSushi'), ('CDC', 'CirculoCredito'), ('BM', 'Bocamel'), ('UCO', 'PreparatoriaUco')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('CORP', 'Corporate'), ('SM', 'ShopSmall'), ('AU', 'AllUsers'), ('PL', 'Platinum'), ('CEN', 'Centurion'), ('UCO', 'PreparatoriaUco')], max_length=5)),
            ],
        ),
    ]
