# Generated by Django 2.2.2 on 2019-07-01 01:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mdesigner', '0003_assets_email_empresa_proyecto_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='fechaMail',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechaProyecto',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='mdesigner.usuario'),
            preserve_default=False,
        ),
    ]
