# Generated by Django 2.2.2 on 2019-07-02 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdesigner', '0009_auto_20190701_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='fechaMail',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fechaProyecto',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdesigner.Usuario'),
        ),
    ]
